export const UPDATE_GREETING = 'UPDATE_GREETING';
export const SERVICE_SELECTED = 'SERVICE_SELECTED';
export const SERVICE_DESELECTED = 'SERVICE_DESELECTED';
//export const UPDATE_CONTACT = 'UPDATE_CONTACT';